/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue';

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Department: typeof import('./../../src/components/businesses/department.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}

// For TSX support
declare global {
  const Department: (typeof import('./../../src/components/businesses/department.vue'))['default'];
  const RouterLink: (typeof import('vue-router'))['RouterLink'];
  const RouterView: (typeof import('vue-router'))['RouterView'];
  const VanButton: (typeof import('vant/es'))['Button'];
  const VanNavBar: (typeof import('vant/es'))['NavBar'];
  const VanTabbar: (typeof import('vant/es'))['Tabbar'];
  const VanTabbarItem: (typeof import('vant/es'))['TabbarItem'];
}
